### PR TITLE
ExtractText implementation on MuPDFDocument

### PR DESCRIPTION
**Pull request by joslat**
As discussed, here is a sample implementation for ExtractText, optimized it a bit with a StringBuilder as there will be a lot of concatenations :)

### CODE REVIEW

**Comment by joslat** [comment]
to note, I added a .gitignore file but feel free to kick that out. just thought that it won't hurt ;)

**Comment by arklumpus** [comment]
Great, thanks! I will have a look at it and merge.

Is there a particular reason why you are concatenating the lines using spaces rather than using AppendLine?

**Comment by joslat** [comment]
Not really... The main reasoning is as the order is not guaranteed, it did not make much sense to add a line terminator there, as they are not really "lines" on another side the goal is to get all the text for FTS indexing so I also thought this might would/could be better. 
But, haven't tested it.

**Comment by arklumpus** [comment]
Superseded by ddec84e.

**Pull request closed without merging**
